name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build

    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: aarch64-apple-darwin

          # - build: windows-msvc
          #   os: windows-latest
          #   target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          binary_name="rust-action-experiments"

          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          echo "DIR=$dirname" >> $GITHUB_ENV
          binary_suffix=
          if [[ ${{ matrix.target }} == x86_64-pc-windows-* ]]; then
            binary_suffix=".exe"
          fi
          echo moving target/${{ matrix.target }}/release/${binary_name}${binary_suffix} to $dirname
          mv "target/${{ matrix.target }}/release/${binary_name}${binary_suffix}" "$dirname"

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DIR }}
          path: ${{ env.ASSET }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: |
          ls -l artifacts
          mkdir packages
          cp artifacts/* packages
      - uses: softprops/action-gh-release@v2
        with:
          files: packages/*
