name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and upload

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: aarc64-apple-darwin

          - build: windows-gnu
            os: windows-latest
            target: x88_64-pc-windows-gnu

          - build: windows-msvc
            os: windows-latest
            target: x88_64-pc-windows-gnu


    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        uses: cross-rs/cross-rs
        run: cross build --verbose --release --target ${{ matrix.target }}

