name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: aarch64-apple-darwin

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          binary_name="rust-action-experiments"
          dirname="${binary_name}-${VERSION}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            binary_suffix=".exe"
            compress="7z a"
            asset_extension=".zip"
            sha_cmd_template='certutil -hashfile THE_ASSET SHA256'
          else
            binary_suffix=
            compress="tar zcf"
            asset_extension=".tar.gz"
            sha_cmd_template='shasum -a 256 THE_ASSET'
          fi

          mv "target/${{ matrix.target }}/release/${binary_name}${binary_suffix}" "$dirname"
          ASSET=${dirname}${asset_extension}
          ${compress} "$ASSET" "$dirname"
          sha_cmd=${sha_cmd_template/THE_ASSET/${ASSET}}
          ${sha_cmd} > "$ASSET.sha256"
          echo "ASSET=$ASSET" >> $GITHUB_ENV
          echo "CHECKSUM=$ASSET.sha256" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            ${{ env.ASSET }}
            ${{ env.CHECKSUM }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: |
          mkdir packages
          for d in artifacts/*; do
            cp $d/* packages
          done
      - uses: softprops/action-gh-release@v2
        with:
          files: packages/*
